version: "3.2"
services:
  ch:
    build:
        context: .
        dockerfile: clickhouse.Dockerfile
        cache_from:
            - yandex/clickhouse-server:latest
    ports:
        - "8123:8123"
    volumes:
        -  ch_db:/var/lib/clickhouse
    networks:
        - clickhouse
    restart: always
  tabix:
    image: spoonest/clickhouse-tabix-web-client
    ports:
        - "8124:80"
    networks:
        - clickhouse
    depends_on:
        - ch
    restart: always
  mysql:
    image: mariadb
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_TCP_PORT=3306
    ports:  
        - "3306:3306"
    volumes:
        -  mysql:/var/lib/mysql
    networks:
        - mysql
    restart: always

networks:
    clickhouse:
    mysql:
    
volumes:
    ch_db:
    mysql: