version: "3.2"
services:
  clickhouse:
    build:
        context: .
        dockerfile: clickhouse.Dockerfile
        cache_from:
            - yandex/clickhouse-server:latest
    ports:
        - "8123:8123"
        - "9000:9000"
        - "9009:9009"
    ulimits:
        nproc: 65535
        nofile:
            soft: 262144
            hard: 262144
    volumes:
        -  clickhouse_store:/var/lib/clickhouse
    environment:
        - CLICKHOUSE_USER=admin
        - CLICKHOUSE_PASSWORD=admin
    networks:
        - clickhouse_net
    restart: always
  tabix:
    image: spoonest/clickhouse-tabix-web-client
    ports:
        - "8124:80"
    networks:
        - clickhouse_net
    environment:
        - USER=admin
        - PASSWORD=admin
    depends_on:
        - clickhouse
    restart: always

networks:
    clickhouse_net:
    
volumes:
    clickhouse_store:
